<?php

namespace App\Repositories;

use App\Media\ThumbUploads;
use App\Models\Serie;
use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Repositories\SerieRepository;



/**
 * Class SerieRepositoryEloquent
 * @package namespace App\Repositories;
 */
class SerieRepositoryEloquent extends BaseRepository implements SerieRepository
{
    use ThumbUploads;

    public function create(array $attributes)
    {
        //Retira informacao de file
        $model= parent::create(array_except($attributes,'thumb_file')); // TODO: Change the autogenerated stub
        $this->uploadThumb($model->id, $attributes['thumb_file']);
        return $model;
    }


    public function update(array $attributes, $id)
    {
        $model = parent::update(array_except($attributes,'thumb_file'), $id); // TODO: Change the autogenerated stub
        if(isset($attributes['thumb_file']))
            $this->uploadThumb($model->id, $attributes['thumb_file']);

        return $model;
    }

    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Serie::class;
    }


    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }


}
