<?php

namespace App\Repositories;

use Jrean\UserVerification\Facades\UserVerification;
use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Models\User;

/**
 * Class UserRepositoryEloquent
 * @package namespace App\Repositories;
 */
class UserRepositoryEloquent extends BaseRepository implements UserRepository
{

    public function create(array $attributes)
    {
        $attributes['role'] = User::ADMIN;
        if(isset($attributes['password'])) {
            $attributes['password'] = User::generatePassword($attributes['password']);
        }else{
            $attributes['password'] = User::generatePassword();
        }
        $model = parent::create($attributes);

        UserVerification::generate($model);
        UserVerification::send($model,'Ative sua conta Now!');

        return $model; // TODO: Change the autogenerated stub
    }


    public function update(array $attributes, $id)
    {
        $attributes['role'] = User::ADMIN;

        if(isset($attributes['password'])) {
            $attributes['password'] = User::generatePassword($attributes['password']);
        }else{
            $attributes = array_except($attributes,['password']);
        }
        return parent::update($attributes, $id); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id);
    }

    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return User::class;
    }

    

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }
}
